debug: false


spring:
  data:
    rest:
      basePath: "/rest"
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  servlet:
    multipart:
      enabled: true



server:
  compression:
    enabled: true